# Generated by Django 2.1.15 on 2025-07-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=50)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=10, unique=True)),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField()),
                ('birthday', models.DateField()),
                ('valid', models.BooleanField(default=True)),
                ('department_code', models.ForeignKey(db_column='department_code', on_delete=django.db.models.deletion.CASCADE, to='home.Department')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('job_name', models.CharField(max_length=50)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_code',
            field=models.ForeignKey(db_column='job_code', on_delete=django.db.models.deletion.CASCADE, to='home.Job'),
        ),
    ]
